"""
fabric_client.py
─────────────────────────────────────────────────────────────────────────────
Bridge between the Python ingestion service and Hyperledger Fabric.

ACADEMIC CONTEXT
────────────────
Hyperledger Fabric exposes its peer nodes via gRPC (Google Remote Procedure
Call). gRPC is a binary protocol built on top of HTTP/2, much faster than
REST/JSON but requires a specific client library to use.

Anthropic provides the official Python SDK for Fabric called:
  fabric-sdk-py  →  the low-level SDK (complex, deprecated)
  fabric-gateway →  the modern, recommended Gateway API (what we use here)

The Gateway API (introduced in Fabric v2.4) follows a simple pattern:
  1. Open a gRPC channel to a peer
  2. Authenticate using an X.509 identity (certificate + private key)
  3. Get a reference to a Network (channel) → Contract (chaincode)
  4. Call submit_transaction() or evaluate_transaction()

KEY CONCEPTS
────────────
  X.509 Identity   — your cryptographic ID on the network. Contains a
                     certificate (public) and a private key (secret).
                     Generated by the Fabric CA during network setup.

  MSP (Membership  — the component that maps certificates to organizations.
  Service Provider)  Org1MSP means "this identity belongs to Org1".

  TLS Root Cert    — used to verify that the peer you're connecting to is
                     genuine and not an impersonator (man-in-the-middle).

  submit_transaction()   — sends a transaction through the full Fabric
                           lifecycle: endorse → order → commit → ledger.
                           Slower (~500ms) but permanently recorded.

  evaluate_transaction() — sends a query directly to the peer. No ordering,
                           no consensus. Instant read from the world state.
                           Does NOT write anything to the ledger.
"""

## NEW COMMENTS ###################################

"""

WHY SUBPROCESS INSTEAD OF THE SDK?
────────────────────────────────────
The official Fabric Python Gateway SDK is not published on PyPI.
Instead of fighting with SDK installation, we call the `peer` CLI binary
directly — the exact same commands you already tested and confirmed working
in Step 5 of the session.

This is a legitimate pattern used in many real integrations.
The `peer` binary handles all gRPC, TLS, and signing internally.

WHAT THIS FILE DOES:
  store_hash()   → runs: peer chaincode invoke ... StoreHash
  verify_hash()  → runs: peer chaincode query  ... VerifyHash

No extra pip packages needed — only the `peer` binary that is already
installed in ~/hyperFabric/fabric-samples/bin/
"""

"""

CHAINCODE SIGNATURES THIS CLIENT TARGETS (iot_contract.go v1.2)
────────────────────────────────────────────────────────────────
  StoreHash(recordID, deviceID, hash string, timestamp int64) error
  VerifyHash(recordID, candidateHash string) (bool, error)
  GetRecord(recordID string)               (*IntegrityRecord, error)

RECORD ID CONVENTION
────────────────────
The chaincode uses a single opaque `recordID` as the ledger key. To make
keys deterministic and collision-free, we build them client-side as:
    record_id = f"{device_id}_{timestamp}_{seq}"
Including `seq` (the per-mote monotonic counter) guarantees uniqueness
even when two readings arrive in the same second.

NOTE: the v1.2 chaincode does NOT enforce key uniqueness — a duplicate
recordID will silently overwrite the previous record. Therefore the
client is responsible for choosing collision-free IDs.
"""

import json
import os
import subprocess

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1 — Paths & Network Configuration
# ─────────────────────────────────────────────────────────────────────────────

FABRIC_SAMPLES = os.path.expanduser("~/hyperFabric/fabric-samples")
TEST_NETWORK   = os.path.join(FABRIC_SAMPLES, "test-network")
PEER_BIN       = os.path.join(FABRIC_SAMPLES, "bin", "peer")

CHANNEL_NAME   = "mychannel"
CHAINCODE_NAME = "iot-integrity"

# Orderer
ORDERER_ADDRESS      = "localhost:7050"
ORDERER_TLS_HOSTNAME = "orderer.example.com"
ORDERER_CA = os.path.join(
    TEST_NETWORK,
    "organizations/ordererOrganizations/example.com"
    "/orderers/orderer.example.com/msp/tlscacerts"
    "/tlsca.example.com-cert.pem",
)

# Org1 (signing identity + endorsing peer)
ORG1_BASE = os.path.join(
    TEST_NETWORK,
    "organizations/peerOrganizations/org1.example.com",
)
ORG1_PEER_ADDRESS = "localhost:7051"
ORG1_MSP_ID       = "Org1MSP"
ORG1_TLS_CERT     = f"{ORG1_BASE}/peers/peer0.org1.example.com/tls/ca.crt"
ORG1_MSP_CONFIG   = f"{ORG1_BASE}/users/Admin@org1.example.com/msp"

# Org2 (second endorser; default policy requires both orgs)
ORG2_BASE = os.path.join(
    TEST_NETWORK,
    "organizations/peerOrganizations/org2.example.com",
)
ORG2_PEER_ADDRESS = "localhost:9051"
ORG2_TLS_CERT     = f"{ORG2_BASE}/peers/peer0.org2.example.com/tls/ca.crt"


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2 — Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _build_env() -> dict:
    """
    Return a copy of the current environment populated with all Fabric
    variables the `peer` CLI needs. Building a fresh dict per call avoids
    polluting the long-running ingestion process's own environment.
    """
    env = os.environ.copy()
    env["PATH"] = os.path.join(FABRIC_SAMPLES, "bin") + ":" + env.get("PATH", "")
    env["FABRIC_CFG_PATH"]             = os.path.join(FABRIC_SAMPLES, "config")
    env["CORE_PEER_TLS_ENABLED"]       = "true"
    env["CORE_PEER_LOCALMSPID"]        = ORG1_MSP_ID
    env["CORE_PEER_ADDRESS"]           = ORG1_PEER_ADDRESS
    env["CORE_PEER_TLS_ROOTCERT_FILE"] = ORG1_TLS_CERT
    env["CORE_PEER_MSPCONFIGPATH"]     = ORG1_MSP_CONFIG
    return env


def make_record_id(device_id: str, timestamp: int, seq: int = 0) -> str:
    """
    Construct the deterministic ledger key for one reading.

    Centralising this in one place means the write path (store_hash) and
    the read path (verify_hash, GetRecord queries) cannot drift apart.
    """
    return f"{device_id}_{timestamp}_{seq}"


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3 — Public API
# ─────────────────────────────────────────────────────────────────────────────

def store_hash(device_id: str, timestamp: int, payload_hash: str,
               seq: int = 0) -> bool:
    """
    Anchor a sensor reading's hash on the Fabric ledger.

    Calls:
      peer chaincode invoke ... -c '{"function":"StoreHash",
                                     "Args":[record_id, device_id,
                                             hash, timestamp]}'

    Goes through the full lifecycle: Endorse (both peers simulate) →
    Order (orderer sequences) → Commit (block written). ~500 ms typical.

    Both Org1 and Org2 peers are passed as --peerAddresses because the
    default endorsement policy of the test-network requires both signatures.

    Returns True if the transaction was committed, False on any error.
    Failure is non-fatal — the caller (ingestion service) continues to
    write to SQLite, and `reanchor.py` can replay missed records later.
    """
    record_id = make_record_id(device_id, timestamp, seq)

    chaincode_args = json.dumps({
        "function": "StoreHash",
        # Order matters — must match the Go signature exactly:
        #   StoreHash(recordID, deviceID, hash string, timestamp int64)
        "Args": [record_id, device_id, payload_hash, str(timestamp)],
    })

    cmd = [
        PEER_BIN, "chaincode", "invoke",
        "-o", ORDERER_ADDRESS,
        "--ordererTLSHostnameOverride", ORDERER_TLS_HOSTNAME,
        "--tls", "--cafile", ORDERER_CA,
        "--channelID", CHANNEL_NAME,
        "--name",      CHAINCODE_NAME,
        "--peerAddresses", ORG1_PEER_ADDRESS,
        "--tlsRootCertFiles", ORG1_TLS_CERT,
        "--peerAddresses", ORG2_PEER_ADDRESS,
        "--tlsRootCertFiles", ORG2_TLS_CERT,
        "-c", chaincode_args,
        # Block until the transaction is committed to a block; without this,
        # invoke returns as soon as the orderer accepts it, which can give a
        # false "success" if the commit later fails.
        "--waitForEvent",
    ]

    try:
        result = subprocess.run(
            cmd, env=_build_env(),
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            print(f"[Fabric]  ✅ Anchored  rid={record_id}  "
                  f"hash={payload_hash[:16]}…")
            return True
        else:
            print(f"[Fabric]  ⚠️  store_hash failed (rid={record_id})")
            print(f"           stderr: {result.stderr.strip()[:200]}")
            return False
    except subprocess.TimeoutExpired:
        print(f"[Fabric]  ⚠️  store_hash timed out after 30s (rid={record_id})")
        return False
    except Exception as e:
        print(f"[Fabric]  ⚠️  store_hash error: {e}")
        return False


def verify_hash(device_id: str, timestamp: int, payload_hash: str,
                seq: int = 0) -> bool:
    """
    Check whether the candidate hash matches what is on the Fabric ledger.

    Calls:
      peer chaincode query ... -c '{"function":"VerifyHash",
                                    "Args":[record_id, candidate_hash]}'

    Query is READ-ONLY: the peer simulates the chaincode locally and returns
    the result. No orderer, no consensus, no block written. ~50 ms typical.

    TAMPER DETECTION SEMANTICS
    ──────────────────────────
    At ingest time:
        hash_original = SHA256(canonical_json)
                          → written to BOTH SQLite and Fabric.

    At verify time, the caller recomputes the hash from the current SQLite
    row contents and passes it here. The chaincode compares this candidate
    against the immutable on-chain hash:
        match  → INTACT
        differ → TAMPERED  (a field of the row was modified after ingest)

    Returns True if INTACT, False if TAMPERED or if the record is not found.
    """
    record_id = make_record_id(device_id, timestamp, seq)

    chaincode_args = json.dumps({
        "function": "VerifyHash",
        # Order matters — must match the Go signature exactly:
        #   VerifyHash(recordID, candidateHash string) (bool, error)
        "Args": [record_id, payload_hash],
    })

    cmd = [
        PEER_BIN, "chaincode", "query",
        "--channelID", CHANNEL_NAME,
        "--name",      CHAINCODE_NAME,
        "-c", chaincode_args,
    ]

    try:
        result = subprocess.run(
            cmd, env=_build_env(),
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode != 0:
            print(f"[Fabric]  ⚠️  verify_hash query failed: "
                  f"{result.stderr.strip()[:200]}")
            return False

        # The chaincode's VerifyHash returns the literal string "true"/"false".
        output = result.stdout.strip().lower()
        intact = (output == "true")

        status = "✅ INTACT" if intact else "🚨 TAMPERED"
        print(f"[Fabric]  {status}  rid={record_id}")
        return intact

    except subprocess.TimeoutExpired:
        print(f"[Fabric]  ⚠️  verify_hash timed out (rid={record_id})")
        return False
    except Exception as e:
        print(f"[Fabric]  ⚠️  verify_hash error: {e}")
        return False