services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "8883:8883"     # TLS
      # - "1883:1883"   # plaintext — remove for final
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/certs:ro