# infra/mosquitto.conf
#listener 1883
#allow_anonymous true

#You keep port 1883 open temporarily for backward compatibility during the migration
#Then close it once both gateway and ingestion use 8883.
#For the final demo, remove the 1883 listener entirely

listener 8883
allow_anonymous true
cafile   /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile  /mosquitto/certs/server.key